server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://database-1.cfx9zaui0lmn.us-east-1.rds.amazonaws.com/BabyCare_wxj?characterEncoding=utf-8&serverTimezone=UTC
#    url: jdbc:mysql://database-1.cfx9zaui0lmn.us-east-1.rds.amazonaws.com/BabyCare?characterEncoding=utf-8&serverTimezone=UTC
    username: admin
    password: woshiren211
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update

jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "ssw555" #密钥
  expireTime: 60 #token有效时间 (分钟) 建议一小时以上

